backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - label: 'Materi'
    name: 'materi'
    folder: 'materi'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
